# Etapa 1: Construir el proyecto con Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Correr el proyecto
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/TU_ARCHIVO.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]