spring.application.name=Back
server.port=8081

 # Conexión a PostgreSQL (Las variables) 
spring.datasource.driver-class-name=org.postgresql.Driver
    #Coloca tu URL de conexión, usuario y contraseña aquí
spring.datasource.url=jdbc:postgresql://localhost:5432/SistemaVentasDB 
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT (Las variables)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000