spring.application.name=Back
server.port=8081

#Configuracion sql
spring.datasource.url=jdbc:mysql://localhost:3306/TiendaDonPepe?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12Abril+

# Configuracion con JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true